### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by vani2795** [mikelduke/phpGPS#2]
Warning: mysqli_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known. in C:\xampp\htdocs\phpGPS-master\src\phpGPS.php on line 34

Warning: mysqli_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: No such host is known. in C:\xampp\htdocs\phpGPS-master\src\phpGPS.php on line 34
Failed to connect to db: 2002Error connecting to user system

**Comment by mikelduke** [comment]
You need to configure to database host and connection info in the phpGPS_Settings.php file correctly. The default is DATABASE URL which is not real.

https://github.com/mikelduke/phpGPS/blob/master/src/phpGPS_Settings.php
