### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by tohfaansari** [mikelduke/phpGPS#3]
Hi

I am beginner to php and mysql. I have installed you phpGPS project on my system. I am able to create the back-end that is install.php. After this I cant figure out the flow and how to go about it to completely implement this . Kindly brief me about this ASAP.

Thanks,

**Comment by PYP1** [comment]
Hi, Was the issue resolved? How did you fix it?

**Comment by mikelduke** [comment]
Once the app is running, you add an owner, add a device linked to the owner, add setup the first path. After that, devices can hit the update url with their device id and other info filled out, and it will get added to the path on the map.

**Comment by PYP1** [comment]
Thanks Mike.

Do we not need any license for getting it running?
It doesn't seem to be working for us though.

Thanks!
Dhanashree

**Comment by mikelduke** [comment]
No, you don't need one, everything is open source.

**Comment by PYP1** [comment]
Ok... Thanks..let me check it once again on Monday.

Thanks for the help!!
