### ISSUE TITLE
Application Not working

### ISSUE THREAD

**Issue by PYP1** [mikelduke/phpGPS#4]
Hi,
I have installed all the required pre requisites and packages from the code.
the sql part worked fine.
but after logging in, i can only see the top part of the menu.
Is there anything missing here.
Please help as I am totally new to PHP and Mysql.
And it has taken a lot of installation / uninstallation to get this website running.
![capture](https://user-images.githubusercontent.com/40353525/41526381-5c7d9ad6-72e4-11e8-939c-aa775e0fbbcd.JPG)

Thanks so much.

**Comment by mikelduke** [comment]
Looks like you need boostrap for js and css. I changed the templates to use the bootstrap cdn, so now it does not need to be downloaded.

I also added a vagrant config. If you have vagrant and virtualbox installed, it will configure a vm with the app installed and a database.
