### ISSUE TITLE
Role of visual box

### ISSUE THREAD

**Issue by thedarkviber** [mikelduke/phpGPS#7]
I tried to run this program but i  don't  know about the virtual box and vagrant can anyone tell me why it is used and how.

**Comment by Didza** [comment]
You can just use the Sql route with your browser. That works too.

**Comment by dpoulson** [comment]
Virtualbox/vagrant are just a way of running a virtual machine on your computer that automatically sets up an instance of the application for demo/testing purposes. Rather than actually setting it up properly.
